### PR TITLE
v1.1.2 fixed #30

### LINKED ISSUE #30: NPM Package does not get the latest changes
Hello.

I have been trying to update my project which uses the android-fastboot npm package to flash the Pixel 7 and 7 Pro devices.
I have been seen the fastboot.js repo that there are updates specifically for these devices but they were done after the 1.1.1 version update. And I can also see that the latest version available for android-fastboot is 1.1.1 on both npm and on yarn.

Is this correct or do the packages need to be updated or am I doing something wrong?
Can anyone please advise?

Thanks

### PR DESCRIPTION
**Pull request by shaikrilwan**

### CODE REVIEW

**Review by aathiv — APPROVED** [review]

**Comment by ehte92** [comment]
Hi @kdrag0n , the build failed and because of that the npm package still does not reflect the changes.

**Comment by kdrag0n** [comment]
It's the GitHub Pages deployment that failed. I published 1.1.3 to npm manually: https://www.npmjs.com/package/android-fastboot?activeTab=versions

**Comment by thestinger** [comment]
You can manually run the actions again. I sometimes have to do that with their arm64 Ubuntu runner since it times out connecting to the repositories for some reason.

**Comment by kdrag0n** [comment]
Yep, it succeeded this time.

**Pull request closed without merging**
